config/routes.rb
Rails.application.routes.draw do
  resources :albums do
    collection do
      delete "delete_image"
    end
  end
  devise_for :users
  resources :home

  get 'home/about'
  root "home#index"
  get 'tags/:tag', to: 'home#index', as: 'tag'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_one_attached :cover_photo
    has_many_attached :photos
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    belongs_to :user

    def self.tagged_with(name)
      Tag.find_by_name!(name: name).albums
    end

    def all_tags=(names)
        self.tags = names.split(",").map do |name|
          Tag.where(name: name).first_or_create!
        end
    end

    
    def all_tags
      tags.map(&:name).join(", ")
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :albums, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /albums or /albums.json
  def index
    #@albums = current_user.albums
    if current_user
      albums = current_user.albums
    else
      albums = Album.all
    end
    @q = albums.ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = current_user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back(fallback_location: albums_url)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description, :published, :cover_photo, :all_tags, :photos => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  def set_search
    @q=Album.search(params[:q])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to albums_path
    end

    if params[:tag]
      @albums = Album.tagged_with(params[:tag])
    else
      @albums = Album.where(published: true)
    end

    @q = Album.where(published: true).ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end

  def show
    @album = Album.find(params[:id])
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_add_photo.html.erb
<%= form_with(model: album) do |form| %>
  <div class="field">
    <%= form.label :Add_more_photos %>
    <%= form.file_field :photos, :multiple => true, class:"form-control" %>
  </div><br>

  <div>
    <%= form.submit  class:"btn btn-info"%>
  </div><br>
<% end %>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>
      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder: "Title" %>
  </div><br>

  <div class="field">
    <%= form.label :cover_photo %>
    <%= form.file_field :cover_photo, class:"form-control" %>
  </div><br>

 <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control", placeholder: "Description" %>
  </div><br>

  <div class="field form-group">
    <%= form.label :tag %>
    <%= form.text_field :all_tags, class:"form-control", placeholder: "Tags (comma seperated values)" %>
  </div><br>  

  <div class="field">
    <%= form.label :photos %>
    <%= form.file_field :photos, :multiple => true, class:"form-control" %>
  </div><br>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div><br>

  <div>  
    <%= form.number_field :user_id, id: :album_user_id, type: :hidden, class:"form-control", value: current_user.id  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-info" %>
  </div><br>
<% end %>

app/views/albums/edit.html.erb
<br><h1>Editing Album</h1>
<br>

<%= form_with(model: @album) do |form| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% @album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder: "Title" %>
  </div><br>

  <div class="field">
    <%= form.label :new_cover_photo %>
    <%= form.file_field :cover_photo, class:"form-control" %><br>
    <%=image_tag(@album.cover_photo,class:'edit-cover img-fluid')%>
  </div><br>

 <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control", placeholder: "Description" %>
  </div><br>

  <div class="field form-group">
    <%= form.label :tag %>
    <%= form.text_field :all_tags, class:"form-control", placeholder: "Tags (comma seperated values)" %>
  </div><br>  

  <div class="field">
    <%= form.label :photos %>
    <%= form.file_field :photos, :multiple => true, class:"form-control" %>
  </div>
  
  <br><p class="line d-flex align-items-center justify-content-center", style="font-size:20px;">Your Uploaded Pictures</p><br/>

  <div class="row mt-5">
  <% @album.photos.each do |image|%>
    <div class="col-lg-4 my-3">
      <div class="card-body">
        <%= image_tag(image,class:'picture img-fluid')%>
        <div class="d-flex justify-content-center my-2">
        <%= link_to "Zoom", image, class: "view btn btn-info", target: "_blank"%> 
        </div>       
      </div>
    </div>
  <% end %>
</div>


  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div><br>

  <div class="actions">
    <%= form.submit class:"btn btn-info" %>
  </div><br>
<% end %><br>


<%= link_to 'Show', @album, class:"btn btn-info mx-1"%>
<%= link_to 'Back', albums_path, class:"btn btn-danger" %><br><br>
 

app/views/albums/index.html.erb
<br/><p class="line d-flex align-items-center justify-content-center", style="font-size:20px;">GALLERY APP : Your Added Albums</p><br/>
<div class="input-group">
  <%= search_form_for @q do |f| %>
    <div class="form-outline d-flex justify-content-center">
      <%= f.search_field :tags_name_cont, class:"form-control me-2", type:"search", placeholder:"Search tags" %>
        <button type="button" class="btn btn-success">
        <i class="fas fa-search"></i>
      </button>
    </div>
  <% end %>
</div><br>

<div class= 'row'>
<%@albums.each do |album|%>
  <div class="col-md-4 ">
    <div class="card">
       <div class="card-header text-center"> 
        <%= link_to edit_album_path(album), class:"left" do %> 
        <i class="fas fa-edit"></i>
        <% end %>
        <span class="center"><%= album.title%></span>
        <%= link_to  album, method: :delete, data: { confirm: 'Are you sure?' }, class:"right" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </div>
      <div class="card-body shadow p-3 mb-5 bg-white rounded">
          <%= link_to album do %>
            <%= image_tag(album.cover_photo, class:'img-fluid',style:"height:16rem; width:100%;")%>
          <% end %>
      </div>
      <div class="new card-footer">
        <strong>Description: </strong><%=album.description %>
        <br><strong>Tags: </strong><%=album.all_tags %>
      </div>
    </div>
</div>
<%end%>
</div>
<br>

app/views/albums/new.html.erb
<br><h1>New Album</h1><br>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path, class:"btn btn-danger mb-4" %>

app/views/albums/show.html.erb
<div class= 'row'>
  <div class="col-md-12">
    <div class="card">
      <div class="card-header text-center">
        <%= @album.title %>
      </div>
      <div class="card-body">
        <%=image_tag(@album.cover_photo,class:'img-fluid')%>
      </div>
      <div class="card-footer">
        <strong>Description: </strong><%= @album.description %>
      </div>
    </div>
  </div>
</div><br>
<h1 class="d-flex align-items-center justify-content-center">All Photos</h1><br>
  <div class= 'row'>
  <%@album.photos.each do |image|%>
  <div class="col-md-3">
    <div class="card-header shadow p-3 mb-5 bg-white rounded">
      <%= link_to image, class:"left-photo" do %> 
        <i class="fas fa-search-plus"></i>
      <% end %>
      <%= link_to  delete_image_albums_path(id: image.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"right-photo" do %>
        <i class="fas fa-trash"></i>
      <% end %>
      <div class="card-body">
        <%=image_tag(image,class:'picture img-fluid')%>
      </div>                                                                                            
    </div>
  </div>
  <%end%>
</div>
 <%= render "add_photo", album: @album %>

app/views/home/index.html.erb
<br/><p class="line d-flex align-items-center justify-content-center", style="font-size:20px;">GALLERY APP : User Published Albums</p><br/>

<div class="input-group">
  <%= search_form_for @q do |f| %>
    <div class="form-outline d-flex">
      <%= f.search_field :tags_name_cont, class:"form-control me-2", type:"search", placeholder:"Search tags" %>
        <button type="button" class="btn btn-success">
        <i class="fas fa-search"></i>
      </button>
    </div>
  <% end %>
</div><br>

<div class= 'row'>
<%@albums.each do |album|%>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header text-center">
        <%= album.title %>
      </div>
      <div class="card-body">
        <%= link_to album_path(id: album.id) do %>
        <%= image_tag(album.cover_photo,class:'img-fluid',style:"height:16rem;")%>
        <% end %>
      </div>
      <div class="new card-footer">
        <strong>Description: </strong><%= album.description %>
        <br><strong>Tags: </strong><%= album.all_tags %>
        <br><strong>Number Of Photos: </strong><%= album.photos.count %>
      </div><br>  
    </div>
</div>
<%end%>
</div>
<br>

app/views/home/show.html.erb
<h1 class="my-3">Description:</h1>
<p class="lead my-2"><%= @album.description %></p>
<div class="row mt-5">
  <% @album.photos.each do |image|%>
    <div class="col-lg-4 my-3">
      <div class="card-body">
        <%= image_tag(image,class:'picture img-fluid')%>
        <div class="d-flex justify-content-center my-2">
        <%= link_to "View", image, class: "view btn btn-info", target: "_blank"%> 
        </div>       
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_alerts.html.erb
<br><div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
  <%= render partial: "shared/navbar" %> 
  <div class="container">  
  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>
  <%= yield %>
  </div>
  <%= render partial: "shared/footer" %>
  
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="newfooter text-center text-lg-start" style="border:1px solid black;">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="https://www.facebook.com" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://www.twitter.com" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.google.com" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="https://www.instagram.com" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            COMPANY NAME
          </h6>
          <p><i class="fas fa-gem me-3"></i>GALLERY</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            ADDRESS
          </h6>
          <p><i class="fas fa-home me-3"></i>New York, NY 100, US</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            EMAIL
          </h6>
          <p><i class="fas fa-envelope me-3"></i>gallery@gmail.com</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            CONTACT
          </h6>
          <p><i class="fas fa-phone me-3"></i> + 01 233 567 58</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->
</footer>

<footer class="text-center text-white" style="background-color: #caced1;">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Images -->
    <section class="">
      <div class="row">
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/111.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/112.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/114.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/115.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/116.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); color:black;">
    © 2022 Copyright :
    <a class="text-white" href="#" style="text-decoration:none; color:black;"> GALLERY </a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <i class="fas fa-camera-retro mx-1"></i><a class="navbar-brand" href="#">GALLERY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link " %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to " New Album", new_album_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In ", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="account" >
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn btn-info mx-1' %> 
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>